name: Sync README to Docker Hub

on:
  push:
    branches: [ main ]
    paths:
      - README.md
      - .github/workflows/dockerhub-readme.yml
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Docker Hub description from README.md
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: hoseiny/terminogrid
          readme-filepath: README.md
